[[main]]
name = "Home"
url = "#about"
weight = 10

[[main]]
name = "Posts"
url = "#posts"
weight = 20

[[main]]
name = "Projects"
url = "#projects"
weight = 30

#[[main]]
#name = "Talks"
#url = "#talks"
#weight = 40

[[main]]
name = "Publications"
url = "#featured"
weight = 50

[[main]]
name = "Contact"
url = "#contact"
weight = 60
